name: Run checks & tests

on:
    push:
        branches:
            - "master"
            - "main"
            - "test"
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"

            - name: Install dependencies
              run: .github/workflows/install_deps.sh

            - name: Build
              run: make vendor && make ankiweb

            - name: Run checks
              run: uv run -- pre-commit run --all-files

            - name: Run tests
              run: make test
